<template>
	<Layout icon="file-alt" title="terms_gdpr">
		<Bloc>
			<div v-for="(value, key) in $t('gdpr')" :key="key">
				<div v-if="key.endsWith('title')" class="mb-5">
					<h2 v-if="key.split('_').length === 2">{{ key.split("_")[0] }} {{ value }}</h2>
					<h3 v-if="key.split('_').length === 3">{{ key.split("_")[0] }}.{{ key.split("_")[1] }} {{ value }}</h3>
				</div>
				<div v-else-if="key.endsWith('content')" class="mb-5" v-html="value"></div>
			</div>
		</Bloc>
	</Layout>
</template>

<script>
import Bloc from "@/components/Bloc"
import Layout from "@/components/Layout"

export default {
	name: "TermsGDPR",
	route: {
		name: "terms_gdpr",
		path: "terms/gdpr"
	},
	components: { Bloc, Layout },
	i18n: {
		messages: {
			fr: {
				gdpr: {
					"1_title": "Définition et nature des données à caractère personnel",
					"1_content": "<p>Lors de votre utilisation de notre site, nous pouvons être amenés à vous demander de nous communiquer des données à caractère personnel vous concernant.</p>",
					"2_title": "Objet de la présente charte",
					"2_content": '<p>La présente charte a pour objet de vous informer sur les moyens que nous mettons en œuvre pour collecter vos données à caractère personnel, dans le respect le plus strict de vos droits.</p><p>Nous vous indiquons à ce sujet que nous nous conformons, dans la collecte et la gestion de vos données à caractère personnel, à la loi n° 78-17 du 6 janvier 1978 relative à l\'informatique, aux fichiers et aux libertés, dans sa version actuelle, ainsi qu’au Règlement général de protection des données (ci-après "RGPD").</p>',
					"3_title": "Identité du responsable de la collecte de données",
					"3_content": "<p>Le responsable de la collecte de vos données à caractère personnel est la société Antoine Kahlouche SASU (Cf. Informations légales).</p>",
					"4_title": "Collecte des données à caractère personnel",
					"4_content": "<p>Vos données à caractère personnel sont collectées pour répondre à une ou plusieurs des finalités suivantes :</p><ul><li>Gérer votre accès à certains services accessibles sur le site et leur utilisation,</li><li>Effectuer les opérations relatives à la gestion des clients concernant les contrats, commandes, livraisons, factures, programmes de fidélité, suivis de la relation avec les clients,</li><li>Constituer un fichier de membres inscrits, d'utilisateurs, de clients et prospects,</li><li>Adresser des newsletters, sollicitations et messages promotionnels. Dans le cas où vous ne le souhaiteriez pas, nous vous donnons la faculté d'exprimer votre refus à ce sujet lors de la collecte de vos données;</li><li>Élaborer des statistiques commerciales et de fréquentation de nos services,</li><li>Organiser des jeux concours, loteries et toutes opérations promotionnelles à l'exclusion des jeux d'argent et de hasard en ligne soumis à l'agrément de l'Autorité de Régulation des Jeux en ligne,</li><li>Gérer la gestion des avis des personnes sur des produits, services ou contenus,</li><li>Gérer les impayés et les contentieux éventuels quant à l'utilisation de nos produits et services,</li><li>Respecter nos obligations légales et réglementaires.</li></ul><p>Nous vous informons, lors de la collecte de vos données personnelles, si certaines données doivent être obligatoirement renseignées ou si elles sont facultatives. Nous vous indiquons également quelles sont les conséquences éventuelles d'un défaut de réponse.</p>",
					"5_title": "Destinataires des données collectées",
					"5_content": "<p>Le personnel de notre société, les services chargés du contrôle (commissaire aux comptes notamment) et nos sous-traitants auront accès à vos données à caractère personnel.</p><p>Peuvent également être destinataires de vos données à caractère personnel les organismes publics, exclusivement pour répondre à nos obligations légales, les auxiliaires de justice, les officiers ministériels et les organismes chargés d'effectuer le recouvrement de créances.</p>",
					"6_title": "Cession des données à caractère personnel",
					"6_content": "<p>Vos données à caractère personnel ne feront pas l'objet de cessions, locations ou échanges au bénéfice de tiers, sauf dans le cas d'une prestation commandée explicitement (ex: Inscription à une course).</p>",
					"7_title": "Durée de conservation des données à caractère personnel",
					"7_1_title": "Concernant les données relatives à la gestion de clients et prospects",
					"7_1_content": "<p>Vos données à caractère personnel ne seront pas conservées au-delà de la durée strictement nécessaire à la gestion de notre relation commerciale avec vous. Toutefois, les données permettant d'établir la preuve d'un droit ou d'un contrat, devant être conservées au titre du respect d'une obligation légale, le seront pendant la durée prévue par la loi en vigueur.</p><p>Concernant d'éventuelles opérations de prospection à destination des clients, leurs données pourront être conservées pendant un délai de trois ans à compter de la fin de la relation commerciale.</p><p>Les données à caractère personnel relatives à un prospect, non client, pourront être conservées pendant un délai de trois ans à compter de leur collecte ou du dernier contact émanant du prospect.</p><p>Au terme de ce délai de trois ans, nous pourrons reprendre contact avec vous pour savoir si vous souhaitez continuer à recevoir des sollicitations commerciales.</p>",
					"7_2_title": "Concernant les pièces d'identité",
					"7_2_content": "<p>En cas d'exercice du droit d'accès ou de rectification, les données relatives aux pièces d'identité pourront être conservées pendant le délai prévu à l'article 9 du code de procédure pénale, soit un an.</p><p>En cas d'exercice du droit d'opposition, ces données peuvent être archivées pendant le délai de prescription prévu par l'article 8 du code de procédure pénale, soit trois ans.</p>",
					"7_3_title": "Concernant les données relatives aux cartes bancaires",
					"7_3_content": "<p>Les transactions financières relatives au paiement des achats et des frais via le site, sont confiées à un prestataire de services de paiement qui en assure le bon déroulement et la sécurité.</p><p>Pour les besoins des services, ce prestataire de services de paiement peut être amené à être destinataire de vos données à caractère personnel relatives à vos numéros de cartes bancaires, qu'il recueille et conserve en notre nom et pour notre compte.</p><p>Nous n'avons pas accès à ces données.</p><p>Pour vous permettre de réaliser régulièrement des achats ou de régler les frais afférents sur le site, vos données relatives à vos cartes bancaires sont conservées pendant le temps de votre inscription sur le site et à tout le moins, jusqu'au moment où vous réalisez votre dernière transaction.</p><p>En ayant coché sur le site la case expressément prévue à cet effet, vous nous donnez votre consentement exprès pour cette conservation.</p><p>Les données relatives au cryptogramme visuel ou CVV2, inscrit sur votre carte bancaire, ne sont pas stockées.</p><p>Si vous refusez que vos données à caractère personnel relatives à vos numéros de cartes bancaires soient conservées dans les conditions précisées ci-dessus, nous ne conserverons pas ces données au-delà du temps nécessaire pour permettre la réalisation de la transaction.</p><p>En tout état de cause, les données relatives à celles-ci pourront être conservées, pour une finalité de preuve en cas d'éventuelle contestation de la transaction, en archives intermédiaires, pour la durée prévue par l'article L 133-24 du Code monétaire et financier, en l'occurrence 13 mois suivant la date de débit. Ce délai peut être étendu à 15 mois afin de prendre en compte la possibilité d'utilisation des cartes de paiement à débit différé.</p>",
					"7_4_title": "Concernant la gestion des listes d'opposition à recevoir de la prospection",
					"7_4_content": "<p>Les informations permettant de prendre en compte votre droit d'opposition sont conservées au minimum trois ans à compter de l'exercice du droit d'opposition.</p>",
					"7_5_title": "Concernant les statistiques de mesure d'audience",
					"7_5_content": "<p>Les informations stockées dans le terminal des utilisateurs ou tout autre élément utilisé pour identifier les utilisateurs et permettant leur traçabilité ou fréquentation ne seront pas conservées au-delà de 6 mois.</p>",
					"8_title": "Sécurité",
					"8_content": "<p>Nous vous informons prendre toutes précautions utiles, mesures organisationnelles et techniques appropriées pour préserver la sécurité, l'intégrité et la confidentialité de vos données à caractère personnel et notamment, empêcher qu'elles soient déformées, endommagées ou que des tiers non autorisés y aient accès. Nous recourrons ou pouvons recourir également à des systèmes de paiement sécurisé conformes à l'état de l'art et à la réglementation applicable.</p>",
					"9_title": "Cookies",
					"9_content": "<p>Les cookies sont des fichiers textes, souvent cryptés, stockés dans votre navigateur. Ils sont créés lorsque le navigateur d'un utilisateur charge un site internet donné : le site envoie des informations au navigateur, qui créé alors un fichier texte. Chaque fois que l'utilisateur revient sur le même site, le navigateur récupère ce fichier et l'envoie au serveur du site internet.</p><p>On peut distinguer deux types de cookies, qui n'ont pas les mêmes finalités : les cookies techniques et les cookies publicitaires :</p><ul><li>Les cookies techniques sont utilisés tout au long de votre navigation, afin de la faciliter et d'exécuter certaines fonctions. Un cookie technique peut par exemple être utilisé pour mémoriser les réponses renseignées dans un formulaire ou encore les préférences de l'utilisateur s'agissant de la langue ou de la présentation d'un site internet, lorsque de telles options sont disponibles.</li><li>Les cookies publicitaires peuvent être créés non seulement par le site internet sur lequel l'utilisateur navigue, mais également par d'autres sites internet diffusant des publicités, annonces, widgets ou autres éléments sur la page affichée. Ces cookies peuvent notamment être utilisés pour effectuer de la publicité ciblée, c'est-à-dire de la publicité déterminée en fonction de la navigation de l'utilisateur.</li></ul><p>Nous utilisons des cookies techniques. Ceux-ci sont stockés dans votre navigateur pour une période qui ne peut excéder six mois.</p><p>Nous n'utilisons pas de cookies publicitaires. Toutefois, si nous devions en utiliser à l'avenir, nous vous en informerions au préalable et vous auriez la possibilité le cas échéant de désactiver ces cookies.</p><p>Nous utilisons ou pouvons utiliser Google Analytics qui est un outil statistique d'analyse d'audience qui génère un cookie permettant de mesurer le nombre de visites sur le site, le nombre de pages vues et l'activité des visiteurs. Votre adresse IP est également collectée pour déterminer la ville depuis laquelle vous vous connectez. La durée de conservation de ce cookie est mentionnée à l'article 7 de la présente charte.</p><p>Nous vous rappelons à toutes fins utiles qu'il vous est possible de vous opposer au dépôt de cookies en configurant votre navigateur. Un tel refus pourrait toutefois empêcher le bon fonctionnement du site.</p>",
					"10_title": "Consentement",
					"10_content": "<p>Lorsque vous choisissez de communiquer vos données à caractère personnel, vous donnez expressément votre consentement pour la collecte et l'utilisation de celles-ci conformément à ce qui est énoncé à la présente charte et à la législation en vigueur.</p>",
					"11_title": "Accès à vos données à caractère personnel",
					"11_content": "<p>Conformément à la loi n° 78-17 du 6 janvier 1978 relative à l'informatique, aux fichiers et aux libertés, ainsi que de RGPD, vous disposez du droit d'accéder à vos données (article 15 du RGPD) pour en obtenir la communication et, le cas échéant, la rectification ou la suppression des données vous concernant (articles 16 et 17 du RGPD), à travers un accès en ligne à votre dossier. Vous pouvez également vous adresser à Antoine Kahlouche SASU (Cf. Informations légales)</p><p>Il est rappelé que toute personne peut, pour des motifs légitimes, demander la limitation au traitement des données la concernant (article 18 du RGPD) ou s'opposer audit traitement (articles 21 et 22 du RGPD).</p><p>Nous vous informerons qu’en cas de rectification ou effacement de vos données à caractère personnel, ainsi que de limitation des traitements, réalisés suite à une demande de votre part, nous notifierons lesdites modifications aux personnes auxquelles nous avons communiqués vos données, à moins qu’une telle communication s’avère impossible (article 19 du RGPD).</p>",
					"12_title": "Portabilité de vos données à caractère personnel",
					"12_content": "<p>Vous disposez d’un droit à la portabilité des données à caractère personnel que vous nous aurez fournies, entendues comme les données que vous avez déclarées activement et consciemment dans le cadre de l’accès et de l’utilisation des services, ainsi que des données générées par votre activité dans le cadre de l’utilisation des services (article 20 du RGPD). Nous vous rappelons que ce droit ne porte pas sur les données collectées et traitées sur une autre base légale que le consentement ou l’exécution du contrat nous liant.</p><p>Ce droit peut être exercé gratuitement, à tout moment, et notamment lors de la fermeture de votre compte sur la Plateforme, afin de récupérer et de conserver vos données à caractère personnel.</p><p>Dans ce cadre, nous vous adresserons vos données à caractère personnel, par tous moyens jugés utiles, dans un format ouvert standard couramment utilisé et lisible par machine, conformément à l’état de l’art.</p>",
					"13_title": "Introduction d’une réclamation devant une autorité de contrôle",
					"13_content": "<p>Vous êtes également informés que vous disposez du droit d’introduire une réclamation auprès d’une autorité de contrôle compétente, (la Commission Nationale Informatique et Libertés pour la France), dans l’Etat membre dans lequel se trouve votre résidence habituelle, votre lieu de travail ou le lieu où la violation de vos droits aurait été commise, si vous considérez que le traitement de vos données à caractère personnel objet de la présente Charte constitue une violation des textes applicables.</p><p>Ce recours pourra être exercé sans préjudice de tout autre recours devant une juridiction administrative ou juridictionnelle. En effet, vous disposez également d’un droit à un recours administratif ou juridictionnel effectif si vous considérez que le traitement de vos données à caractère personnel objet de la présente Charte constitue une violation des textes applicables.</p>",
					"14_title": "Communication relative à une violation de données à caractère personnel",
					"14_content": "<p>Si nous constatons une faille de sécurité dans le traitement de vos données susceptibles d’entraîner un risque élevé pour vos droits et libertés, nous vous en informerons dans les meilleurs délais (article 34 du RGPD). Nous vous détaillerons à cette occasion la nature de la violation rencontrée et les mesures mise en place pour y mettre un terme.</p>",
					"15_title": "Modifications",
					"15_content": "<p>Nous nous réservons le droit, à notre seule discrétion, de modifier à tout moment la présente charte, en totalité ou en partie. Ces modifications entreront en vigueur à compter de la publication de la nouvelle charte. Votre utilisation du site suite à l'entrée en vigueur de ces modifications vaudra reconnaissance et acceptation de la nouvelle charte. A défaut et si cette nouvelle charte ne vous convient pas, vous ne devrez plus accéder au site.</p>",
					"16_title": "Entrée en vigueur",
					"16_content": "<p>La présente charte est entrée en vigueur le 21/02/2020.</p>"
				}
			}
		}
	}
}
</script>

<style scoped></style>
